language: go
go:
  - 1.15.x
dist: xenial
env:
  - GO111MODULE=on

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make docker;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push keratin/authn-server:latest;
    fi
