language: go
go:
  - 1.x
services:
  - mysql
  - postgresql
  - redis-server

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script: make test-ci

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make docker;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push keratin/authn-server:latest;
    fi
