version: '3'
services:
  redis:
    image: redis
    ports:
      - "8701:6379"

  mysql:
    image: mysql:5.7
    ports:
      - "8702:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD
