name: Release

# TODO
# on:
#   release:
#     types: [created]
on: push

jobs:
  linux64:
    name: Compile for Linux64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - run: go mod download

      - name: release version
        run: echo ${GITHUB_REF}

      - name: compile
        run: |
          go build \
            -ldflags '-extldflags -static -X main.VERSION=${GITHUB_REF}' \
            -o dist/authn-linux64
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 1
